### ISSUE TITLE
Stacksize issues

### ISSUE THREAD

**Issue by mystlynx** [NFINIT-Development/nfinit-skyblock#12]
Yesterday started a new world everything brand new and updated and such. 
but today the stacksizes don't go further then 16 and some 32 also in a chest it is the case and in inventory. While it doesn't happen on another account. What could be the issue here?
Also restack doesn't work when filling a barrel for example. It doesn't automatically go to the next stack.

**Comment by knoxhack** [comment]
fixed in 1.2.6
