### ISSUE TITLE
Missing Registries error messages after updating to 1.2.6

### ISSUE THREAD

**Issue by chrisvmake** [NFINIT-Development/nfinit-skyblock#13]
I last played my world last night on 1.2.5
The first error page was about ftbu:leaderboards. The second error page was about careerbees.
I didn't go past the second page.

![image](https://user-images.githubusercontent.com/17837181/37848897-1a8857b4-2eac-11e8-8fa0-a3ab265dc1a7.png)

![image](https://user-images.githubusercontent.com/17837181/37848910-2357480a-2eac-11e8-92aa-1d2e8d8ac57e.png)

**Comment by knoxhack** [comment]
Shouldn't be a problem

**Comment by knoxhack** [comment]
Tiny Progression changed all its id names

**Comment by knoxhack** [comment]
And career bees got removed

**Comment by chrisvmake** [comment]
Awesome. I'll give it a try then. Thank you!
