### ISSUE TITLE
Crashing while watering plants

### ISSUE THREAD

**Issue by mystlynx** [NFINIT-Development/nfinit-skyblock#19]
Heya, 

I have an issue that while watering plants that, are on fertilized farmland and in cropsticks to level them up. 
And using a tiny progressions wateringcan. I get kicked out of my game. It happened in our private server and also when i play single player. 
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity

this is the error it gave me. 

Oh and the weeds are a real pain in the buttocks. I think the weed growth is way to high. 

With kind regards,
Mystlynx

**Comment by knoxhack** [comment]
Fixed and Weeds removed in version 1.2.10
