### ISSUE TITLE
Barrel recipe for marble missing.

### ISSUE THREAD

**Issue by PlacidK** [NFINIT-Development/nfinit-skyblock#29]
There used to be a barrel recipe for marble in 1.2.7 i think it was quartz block in barrel of water.
That recipe isn't in Jei anymore in 1.2.9

**Comment by knoxhack** [comment]
I'll double check that recipe, Im sure I readded it in 1.2.9

**Comment by knoxhack** [comment]
Fixed in version 1.2.10!

**Comment by knoxhack** [comment]
Make sure to update your /scripts folder if updating doesn't fix it
