### ISSUE TITLE
Mini-Coal Crafting Output Priority Request

### ISSUE THREAD

**Issue by 99Blocks** [NFINIT-Development/nfinit-skyblock#31]
Hey again Knox,

Not so much a bug as a question/request.

While trying to change Coal/Charcoal into mini-coal the crafting output only offers the "Base Metals (Char)coal nugget".

I don't mind too much but in the "Fuel" section of JEI, the Base Metals Charcoal ingot only smelts 0.8 of an item while the mini-charcoal smelts 1 item.

Again, don't mind if this is deliberate but it is a bit of a pain ;)

Keep up the good work!

**Comment by knoxhack** [comment]
Fixed in version 1.2.10!
