### ISSUE TITLE
Unable to break down gravel with hammers

### ISSUE THREAD

**Issue by Ladysarajane** [NFINIT-Development/nfinit-skyblock#36]
Okay, I upgraded a world and now I cannot break down gravel into sand with hammers. I tried regular hammers, and ex compressium hammers and same thing when the gravel drops it remains gravel. 
Tried a new world and the same thing.

**Comment by 99Blocks** [comment]
Can confirm, looks like the addition of crushing recipes for stone variants has caused some bugs with gravel>sand>dust progression.

**Comment by knoxhack** [comment]
the 1.2.10 update introduced a new Hammer Recipes progression:
New Progression:
- Cobblestone > Gravel.
- Andesite > Crushed Andesite > Sand.
- Diorite > Crushed Diorite > Dust.
- Granite > Crushed Granite > Red Sand.

**Comment by 99Blocks** [comment]
No problem. If that's the intended progression, is there any way to improve the chances of receiving Diorite (And other stone variant) pebbles from sieving as it makes dust difficult to get hold of.
(Sand is unable to be hammered into dust currently).

Knowing the progression I can make it work for me, but it does make resource gathering and automation a little more complicated. Totally behind it if that's your intentions. ;)

**Comment by knoxhack** [comment]
This change was made from all the feedback I got about the sieves, it was too easy to get resources, some people even complained  about  it. 
And yeah I can bump up the pebbles drops from sieve to help out early game, but once you can afford an Igneous Extruder, It can generate unlimited amounts of any of the stone variants.

**Comment by Ladysarajane** [comment]
Okay, that wasn't clear to me I got crushed andesite when I hammered it didn't realize I needed to hammer it again. Maybe some adjustments to the better questing book to clarify the new progression?

**Comment by 99Blocks** [comment]
Ah cool! So I know what machine to get for automation.

I've never felt the urge to complain about something being too easy but I can see why people would want something different.

Makes the pack more interesting to have different paths for getting resources. Definitely agree to have something in the quest book.

Keep it up Knox!

**Comment by knoxhack** [comment]
The next update will include the updated quests to fit the new progression indeed ^_^
