### ISSUE TITLE
(Just a question)Why no infinite water?

### ISSUE THREAD

**Issue by samuelvelter2** [NFINIT-Development/nfinit-skyblock#39]
I mean, really, why? it's ok if it was in a normal world but in a skyblock..... it does not make any sense.

**Comment by knoxhack** [comment]
To encourage automation using the wooden crucibles that generate water and the fluid pipes or fluid hoppers. 
Ther are also other ways to get infinite water for example the infinite water update for the quantum tank.

**Comment by knoxhack** [comment]
Once you make a auto sapling farms you will be need to automate them to go into barrels automatically using pipes and auto farmers

**Comment by knoxhack** [comment]
Bonsai trees also good for the process

**Comment by knoxhack** [comment]
also Discord is a better place for this kind of things ^^

**Comment by samuelvelter2** [comment]
ok, but could you add a quest explaining this in-game mechanic and giving some solutions? also the well from pam's is a solution

**Comment by knoxhack** [comment]
There is a quest that guides you to get water using crucibles
