### ISSUE TITLE
Quest for Energy Cell (basic) not completing

### ISSUE THREAD

**Issue by Thijmenl** [NFINIT-Development/nfinit-skyblock#4]
Made the Energy cell, but the quest won't complete.
picked it up again, nothing
put some energy in it, nothing
reloaded my game, nothing
dunno what else to do :(

**Comment by Phantasm23** [comment]
I experienced the same thing also.  Newly crafted energy cell, stats as per the quest book, but no joy.

**Comment by knoxhack** [comment]
Fixed on version 1.2.3
