### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by Phantasm23** [NFINIT-Development/nfinit-skyblock#5]
There does not appear to be a way to get vanilla wheat "seeds".  The 2x Wheat recipe makes "Cow Bait" (which is useful).

Agricraft only gives wheat when you harvest it, no seeds.  The seeds are needed for recipes and to feed my chickens so they will lay eggs.

**Comment by knoxhack** [comment]
seeds can be obtained by sifting dirt

https://i.imgur.com/GjewCBA.png
