### ISSUE TITLE
Agricraft... all of it

### ISSUE THREAD

**Issue by Phantasm23** [NFINIT-Development/nfinit-skyblock#6]
I know Agricraft is a new addition to the pack and you are aware of some issues with it, these are just the ones I experienced in case they were different from your list.

- Agricraft Tank does not feed water into the Irrigation channels, so the sprinklers do not work.
- Cross breeding onto cross-crops does not seem to work at all.
- Crops spread onto adjacent empty crop sticks (without the cross crops - this may be correct behaviour)
- When weed crops are broken they yield an Auragold seed.
- Stat enhancement of crops not working due to cross breeding not working.

**Comment by BrendanatorX** [comment]
- Agricraft Wooden Water Tank/Barrel thing also doesn't attach to Liquiducts like it's meant to.
Cross breeding does work, but 90% of the time it makes Aurigold instead.
I did manage to cross breed some Magical Agriculture Emerald Crops until I got 10/10/10 but it took me a while, and It wouldn't change the seed that was planted, the seed harvested would be undiscovered in the agriculture journal and be at 1/1/1 always even if the crop you got it from was anything else, so only the mutated crop and it's clippings are mutated to be anything other than 1/1/1

**Comment by knoxhack** [comment]
Fixed in version 1.2.7
